### ISSUE TITLE
Doesn't work: sudo npm install faye

### ISSUE THREAD

**Issue by jtwb** [faye/faye#17]
Using npm to install faye works, but running " var faye = require('faye'); " gives this error:

```
module:252
        throw new Error("Cannot find module '" + request + "'");
              ^
Error: Cannot find module '/usr/local/lib/node/.npm/faye/0.5.0/package/faye-node'
    at loadModule (module:252:15)
    at require (module:378:12)
    at Object.<anonymous> (/usr/local/lib/node/faye.js:5:18)
    at Module._compile (module:427:23)
    at Module._loadScriptSync (module:437:8)
    at Module.loadSync (module:310:10)
    at loadModule (module:255:16)
    at require (module:378:12)
    at Object.<anonymous> (/Users/benterou/src/teawater/test.js:2:12)
    at Module._compile (module:427:23)
```

The contents of /usr/local/lib/node/.npm/faye/0.5.0/package/ :

```
$ ls /usr/local/lib/node/.npm/faye/0.5.0/package/
History.txt README.rdoc faye-node.js    lib     test
Jakefile    Rakefile    jake.yml    package.json
Manifest.txt    examples    javascript  site
```

There is no "faye-node.js".  Even worse, the file "javascript/faye.js" needs to be processed by jake.

It looks like npm was hoping to install the contents of your build rather than your raw repo, like this: http://faye.jcoglan.com/assets/faye.0-5-1.zip

**Comment by katopz** [comment]
Seem like i've have to build something to get that faye-node.js am i right? 
it should be doc somewhere? Far as i go now is
```shell
Pis-Mac-mini:faye pirsquare$ jake -f --trace
jake aborted.
TypeError: undefined is not a function
    at loadFile (/usr/local/lib/node_modules/jake/lib/loader.js:48:18)
    at EventEmitter.utils.mixin.run (/usr/local/lib/node_modules/jake/lib/jake.js:315:35)
    at Object.<anonymous> (/usr/local/lib/node_modules/jake/bin/cli.js:25:10)
    at Module._compile (module.js:460:26)
    at Object.Module._extensions..js (module.js:478:10)
    at Module.load (module.js:355:32)
    at Function.Module._load (module.js:310:12)
    at Function.Module.runMain (module.js:501:10)
    at startup (node.js:129:16)
    at node.js:814:3
```
any help would be appricitated

**Comment by jcoglan** [comment]
@katopz As documented in https://github.com/faye/faye/blob/master/CONTRIBUTING.md, you need to run `npm run build` these days.
