### ISSUE TITLE
Undefined Method scheme

### ISSUE THREAD

**Issue by JanStevens** [faye/faye#364]
Hello,

I have a server and a client and they play a ping/pong game, I receive the following error on the server after I try to send a pong back to the client from the server:

```
Listening on localhost:9393, CTRL+C to stop
10:12:53.379 [FayeServer][DBG] [HANDSAKE] isj1id84vlaqikiz50n3gkbez8796d1 
10:12:53.380 [FayeServer][DBG] [SUBSCRIBE] isj1id84vlaqikiz50n3gkbez8796d1 -> /printer_server/status/ping 
10:12:57.231 [PingPong][INF] Server sended ping 
/usr/local/opt/rbenv/versions/2.2.0/lib/ruby/gems/2.2.0/gems/faye-1.1.1/lib/faye/transport/transport.rb:20:in `initialize': undefined method `scheme' for #<Faye::Server:0x007fc55b20e680> (NoMethodError)
        from /usr/local/opt/rbenv/versions/2.2.0/lib/ruby/gems/2.2.0/gems/faye-1.1.1/lib/faye/transport/transport.rb:141:in `new'
        from /usr/local/opt/rbenv/versions/2.2.0/lib/ruby/gems/2.2.0/gems/faye-1.1.1/lib/faye/transport/transport.rb:141:in `block (2 levels) in get'
        from /usr/local/opt/rbenv/versions/2.2.0/lib/ruby/gems/2.2.0/gems/faye-1.1.1/lib/faye/transport/local.rb:5:in `call'
        from /usr/local/opt/rbenv/versions/2.2.0/lib/ruby/gems/2.2.0/gems/faye-1.1.1/lib/faye/transport/local.rb:5:in `usable?'
        from /usr/local/opt/rbenv/versions/2.2.0/lib/ruby/gems/2.2.0/gems/faye-1.1.1/lib/faye/transport/transport.rb:139:in `block in get'
        from /usr/local/opt/rbenv/versions/2.2.0/lib/ruby/gems/2.2.0/gems/faye-1.1.1/lib/faye.rb:110:in `call'
        from /usr/local/opt/rbenv/versions/2.2.0/lib/ruby/gems/2.2.0/gems/faye-1.1.1/lib/faye.rb:110:in `block in async_each'
        from /usr/local/opt/rbenv/versions/2.2.0/lib/ruby/gems/2.2.0/gems/faye-1.1.1/lib/faye.rb:117:in `call'
        from /usr/local/opt/rbenv/versions/2.2.0/lib/ruby/gems/2.2.0/gems/faye-1.1.1/lib/faye.rb:117:in `block in async_each'
        from /usr/local/opt/rbenv/versions/2.2.0/lib/ruby/gems/2.2.0/gems/faye-1.1.1/lib/faye.rb:124:in `call'
        from /usr/local/opt/rbenv/versions/2.2.0/lib/ruby/gems/2.2.0/gems/faye-1.1.1/lib/faye.rb:124:in `block in async_each'
        from /usr/local/opt/rbenv/versions/2.2.0/lib/ruby/gems/2.2.0/gems/faye-1.1.1/lib/faye.rb:126:in `call'
        from /usr/local/opt/rbenv/versions/2.2.0/lib/ruby/gems/2.2.0/gems/faye-1.1.1/lib/faye.rb:126:in `async_each'
        from /usr/local/opt/rbenv/versions/2.2.0/lib/ruby/gems/2.2.0/gems/faye-1.1.1/lib/faye/transport/transport.rb:150:in `get'
        from /usr/local/opt/rbenv/versions/2.2.0/lib/ruby/gems/2.2.0/gems/faye-1.1.1/lib/faye/protocol/dispatcher.rb:79:in `select_transport'
        from /usr/local/opt/rbenv/versions/2.2.0/lib/ruby/gems/2.2.0/gems/faye-1.1.1/lib/faye/protocol/client.rb:73:in `handshake'
        from /usr/local/opt/rbenv/versions/2.2.0/lib/ruby/gems/2.2.0/gems/faye-1.1.1/lib/faye/protocol/client.rb:114:in `connect'
        from /usr/local/opt/rbenv/versions/2.2.0/lib/ruby/gems/2.2.0/gems/faye-1.1.1/lib/faye/protocol/client.rb:263:in `publish'
        from /Users/fritz/PP/getin-print-ruby/server/ping_pong.rb:18:in `block in setup_periodic_timer'
        from /usr/local/opt/rbenv/versions/2.2.0/lib/ruby/gems/2.2.0/gems/eventmachine-1.0.7/lib/em/timers.rb:56:in `call'
        from /usr/local/opt/rbenv/versions/2.2.0/lib/ruby/gems/2.2.0/gems/eventmachine-1.0.7/lib/em/timers.rb:56:in `fire'
        from /usr/local/opt/rbenv/versions/2.2.0/lib/ruby/gems/2.2.0/gems/eventmachine-1.0.7/lib/eventmachine.rb:187:in `call'
        from /usr/local/opt/rbenv/versions/2.2.0/lib/ruby/gems/2.2.0/gems/eventmachine-1.0.7/lib/eventmachine.rb:187:in `run_machine'
        from /usr/local/opt/rbenv/versions/2.2.0/lib/ruby/gems/2.2.0/gems/eventmachine-1.0.7/lib/eventmachine.rb:187:in `run'
        from server_app.rb:36:in `<main>'
```

The following code sends a ping every 15 seconds
```ruby
class PingPong
  include Logging
  include Procto.call

  attr_reader :faye
  def initialize
    @faye = FayeServer.instance
  end

  def call
    setup_periodic_timer
    setup_pong_callback
  end

  def setup_periodic_timer
    EM.add_periodic_timer(15) do
      logger.info "Server sended ping"
      faye.get_client.publish("/printer_server/status/ping", {status: :ping})
    end
  end

  def setup_pong_callback
    faye.on_publish do |client_id, channel, data|
      if channel == "/printer_server/status/pong"
        logger.info "Received pong from #{data["mac"]}"
      end
    end
  end

end
```

The FayeServer.instance is a singleton that defines the Faye Server instance, the `get_client` wraps the same method on the faye instance. I use the following options to initialize a `Faye::RackAdapter` instance.

```ruby
 @faye = Faye::RackAdapter.new({
      mount:   '/ws_print',
      timeout: 20,
      ping:    5,
      extensions: [ServerProtection.new]
    })
```

Finally I used a Ruby Server and Ruby Client

**Comment by jcoglan** [comment]
Thanks, this is fixed in https://github.com/faye/faye/commit/cee6a778876da69ff958514b6591e6fcbf7481c1.

**Comment by JanStevens** [comment]
When will the next version be released?

**Comment by jcoglan** [comment]
As soon as I've finished up outstanding issues and had time to do pre-release testing; probably later this month.
