### ISSUE TITLE
NodeJS Promise Reject

### ISSUE THREAD

**Issue by michaeltrimm** [faye/faye#377]
if (promise._state !== PENDING) return;
             ^
      TypeError: Cannot read property '_state' of undefined
          at Promise.reject       (~/node_modules/faye/node/faye-node.js:481:14)
          at Function.Promise.fulfill.Promise.resolve (~/node_modules/faye/node/faye-node.js:465:5)
          at Object.Faye.Transport.Faye.extend.Faye.Class._flush (~/node_modules/faye/node/faye-node.js:1717:18)
          at Object.Faye.Transport.Faye.extend.Faye.Class._flushLargeBatch (~/node_modules/faye/node/faye-node.js:1728:10)
          at Object.Faye.Transport.Faye.extend.Faye.Class.sendMessage (~/node_modules/faye/node/faye-node.js:1696:10)
          at Object.Faye.Dispatcher.Faye.Class._sendEnvelope (~/node_modules/faye/node/faye-node.js:1568:40)
          at null._onTimeout (~/notifier/node_modules/faye/node/faye-node.js:1609:14)
          at Timer.listOnTimeout (timers.js:110:15)

**Comment by jcoglan** [comment]
Could you explain what triggers this error and provide code that reproduces it?

**Comment by jcoglan** [comment]
I think this should be fixed in https://github.com/faye/faye/commit/e252308b77d5b15366ca5d063320178fbb407740.

**Comment by jcoglan** [comment]
Just letting you know 1.2.0 has been released: https://groups.google.com/forum/#!topic/faye-users/_0kTHXciUGs
