### ISSUE TITLE
Faye ruby process crashes when receives "GET /faye?message=1"

### ISSUE THREAD

**Issue by hnatt** [faye/faye#417]
Current master, running with Rack:

```Ruby
# config.ru

require './lib/faye'

bayeux = Faye::RackAdapter.new(:mount => '/faye', :timeout => 25)
run bayeux
```

```bash
$ rackup config.ru -o 0.0.0.0 -s thin
Thin web server (v1.6.4 codename Gob Bluth)
Maximum connections set to 1024
Listening on 0.0.0.0:9292, CTRL+C to stop
```

Then I do a GET request (works also with POST requests)

    $ curl localhost:9292/faye?message=1

The server returns and HTML error page with

```
Rack::Lint::LintError at /faye
Status must be >=100 seen as integer

Ruby	/home/hnatt/.rbenv/versions/2.2.3/lib/ruby/gems/2.2.0/gems/rack-1.6.4/lib/rack/lint.rb: in assert, line 20
Web	GET localhost/faye
```

And then dies with the following words:

```
Rack::Lint::LintError: Status must be >=100 seen as integer
	/home/hnatt/.rbenv/versions/2.2.3/lib/ruby/gems/2.2.0/gems/rack-1.6.4/lib/rack/lint.rb:20:in `assert'
	/home/hnatt/.rbenv/versions/2.2.3/lib/ruby/gems/2.2.0/gems/rack-1.6.4/lib/rack/lint.rb:620:in `check_status'
	/home/hnatt/.rbenv/versions/2.2.3/lib/ruby/gems/2.2.0/gems/rack-1.6.4/lib/rack/lint.rb:51:in `_call'
	/home/hnatt/.rbenv/versions/2.2.3/lib/ruby/gems/2.2.0/gems/rack-1.6.4/lib/rack/lint.rb:37:in `call'
	/home/hnatt/.rbenv/versions/2.2.3/lib/ruby/gems/2.2.0/gems/rack-1.6.4/lib/rack/showexceptions.rb:24:in `call'
	/home/hnatt/.rbenv/versions/2.2.3/lib/ruby/gems/2.2.0/gems/rack-1.6.4/lib/rack/commonlogger.rb:33:in `call'
	/home/hnatt/.rbenv/versions/2.2.3/lib/ruby/gems/2.2.0/gems/rack-1.6.4/lib/rack/chunked.rb:54:in `call'
	/home/hnatt/.rbenv/versions/2.2.3/lib/ruby/gems/2.2.0/gems/rack-1.6.4/lib/rack/content_length.rb:15:in `call'
	/home/hnatt/.rbenv/versions/2.2.3/lib/ruby/gems/2.2.0/gems/thin-1.6.4/lib/thin/connection.rb:86:in `block in pre_process'
	/home/hnatt/.rbenv/versions/2.2.3/lib/ruby/gems/2.2.0/gems/thin-1.6.4/lib/thin/connection.rb:84:in `catch'
	/home/hnatt/.rbenv/versions/2.2.3/lib/ruby/gems/2.2.0/gems/thin-1.6.4/lib/thin/connection.rb:84:in `pre_process'
	/home/hnatt/.rbenv/versions/2.2.3/lib/ruby/gems/2.2.0/gems/thin-1.6.4/lib/thin/connection.rb:53:in `process'
	/home/hnatt/.rbenv/versions/2.2.3/lib/ruby/gems/2.2.0/gems/thin-1.6.4/lib/thin/connection.rb:39:in `receive_data'
	/home/hnatt/.rbenv/versions/2.2.3/lib/ruby/gems/2.2.0/gems/eventmachine-1.0.8/lib/eventmachine.rb:193:in `run_machine'
	/home/hnatt/.rbenv/versions/2.2.3/lib/ruby/gems/2.2.0/gems/eventmachine-1.0.8/lib/eventmachine.rb:193:in `run'
	/home/hnatt/.rbenv/versions/2.2.3/lib/ruby/gems/2.2.0/gems/thin-1.6.4/lib/thin/backends/base.rb:73:in `start'
	/home/hnatt/.rbenv/versions/2.2.3/lib/ruby/gems/2.2.0/gems/thin-1.6.4/lib/thin/server.rb:162:in `start'
	/home/hnatt/.rbenv/versions/2.2.3/lib/ruby/gems/2.2.0/gems/rack-1.6.4/lib/rack/handler/thin.rb:19:in `run'
	/home/hnatt/.rbenv/versions/2.2.3/lib/ruby/gems/2.2.0/gems/rack-1.6.4/lib/rack/server.rb:286:in `start'
	/home/hnatt/.rbenv/versions/2.2.3/lib/ruby/gems/2.2.0/gems/rack-1.6.4/lib/rack/server.rb:147:in `start'
	/home/hnatt/.rbenv/versions/2.2.3/lib/ruby/gems/2.2.0/gems/rack-1.6.4/bin/rackup:4:in `<top (required)>'
	/home/hnatt/.rbenv/versions/2.2.3/bin/rackup:23:in `load'
	/home/hnatt/.rbenv/versions/2.2.3/bin/rackup:23:in `<main>'
127.0.0.1 - - [08/Dec/2015:16:41:33 +0200] "POST /faye?message=1 HTTP/1.1" 500 68552 0.0457
/home/hnatt/code/faye/lib/faye/protocol/server.rb:88:in `[]': no implicit conversion of String into Integer (TypeError)
	from /home/hnatt/code/faye/lib/faye/protocol/server.rb:88:in `handle'
	from /home/hnatt/code/faye/lib/faye/protocol/server.rb:67:in `block (2 levels) in process'
	from /home/hnatt/code/faye/lib/faye/protocol/extensible.rb:23:in `call'
	from /home/hnatt/code/faye/lib/faye/protocol/extensible.rb:23:in `pipe_through_extensions'
	from /home/hnatt/code/faye/lib/faye/protocol/server.rb:66:in `block in process'
	from /home/hnatt/code/faye/lib/faye/protocol/server.rb:65:in `each'
	from /home/hnatt/code/faye/lib/faye/protocol/server.rb:65:in `process'
	from /home/hnatt/code/faye/lib/faye/adapters/rack_adapter.rb:132:in `block in handle_request'
	from /home/hnatt/.rbenv/versions/2.2.3/lib/ruby/gems/2.2.0/gems/eventmachine-1.0.8/lib/eventmachine.rb:976:in `call'
	from /home/hnatt/.rbenv/versions/2.2.3/lib/ruby/gems/2.2.0/gems/eventmachine-1.0.8/lib/eventmachine.rb:976:in `block in run_deferred_callbacks'
	from /home/hnatt/.rbenv/versions/2.2.3/lib/ruby/gems/2.2.0/gems/eventmachine-1.0.8/lib/eventmachine.rb:973:in `times'
	from /home/hnatt/.rbenv/versions/2.2.3/lib/ruby/gems/2.2.0/gems/eventmachine-1.0.8/lib/eventmachine.rb:973:in `run_deferred_callbacks'
	from /home/hnatt/.rbenv/versions/2.2.3/lib/ruby/gems/2.2.0/gems/eventmachine-1.0.8/lib/eventmachine.rb:193:in `run_machine'
	from /home/hnatt/.rbenv/versions/2.2.3/lib/ruby/gems/2.2.0/gems/eventmachine-1.0.8/lib/eventmachine.rb:193:in `run'
	from /home/hnatt/.rbenv/versions/2.2.3/lib/ruby/gems/2.2.0/gems/thin-1.6.4/lib/thin/backends/base.rb:73:in `start'
	from /home/hnatt/.rbenv/versions/2.2.3/lib/ruby/gems/2.2.0/gems/thin-1.6.4/lib/thin/server.rb:162:in `start'
	from /home/hnatt/.rbenv/versions/2.2.3/lib/ruby/gems/2.2.0/gems/rack-1.6.4/lib/rack/handler/thin.rb:19:in `run'
	from /home/hnatt/.rbenv/versions/2.2.3/lib/ruby/gems/2.2.0/gems/rack-1.6.4/lib/rack/server.rb:286:in `start'
	from /home/hnatt/.rbenv/versions/2.2.3/lib/ruby/gems/2.2.0/gems/rack-1.6.4/lib/rack/server.rb:147:in `start'
	from /home/hnatt/.rbenv/versions/2.2.3/lib/ruby/gems/2.2.0/gems/rack-1.6.4/bin/rackup:4:in `<top (required)>'
	from /home/hnatt/.rbenv/versions/2.2.3/bin/rackup:23:in `load'
	from /home/hnatt/.rbenv/versions/2.2.3/bin/rackup:23:in `<main>'
```

It appears to me that only valid decimal and float numbers cause the crash, e.g. `0`, `1.0`, `999`, or `1e10`. Empty value, random text, or numbers in hex notation (e.g. `0xFF`) don't, they are responded with text "Bad request", and the server keeps running.

Tried to reproduce with Puma: the server does not crash, but it doesn't respond and the connection keeps hanging. Webrick also does not crash, and returns empty response with status 200 (which is also not normal, but it's the most acceptable behavior).

**Comment by jcoglan** [comment]
faye-websocket is not compatible with `Rack::Lint` because that middleware doesn't accept WebSocket status codes, or the fake status codes used internally to signal an async response to Thin.

You need to disable this middleware by either using `thin(1)` instead of `rackup(1)`, or running `rackup` with `-E production`.

**Comment by hnatt** [comment]
`rackup` with `-E production` does not help.

```bash
$ curl localhost:9292/faye?message=1
curl: (52) Empty reply from server
```

```bash
$ rackup config.ru -o 0.0.0.0 -s thin -E production
Thin web server (v1.6.4 codename Gob Bluth)
Maximum connections set to 1024
Listening on 0.0.0.0:9292, CTRL+C to stop
/home/hnatt/code/faye/lib/faye/protocol/server.rb:88:in `[]': no implicit conversion of String into Integer (TypeError)
        from /home/hnatt/code/faye/lib/faye/protocol/server.rb:88:in `handle'
        from /home/hnatt/code/faye/lib/faye/protocol/server.rb:67:in `block (2 levels) in process'
        from /home/hnatt/code/faye/lib/faye/protocol/extensible.rb:23:in `call'
        from /home/hnatt/code/faye/lib/faye/protocol/extensible.rb:23:in `pipe_through_extensions'
        from /home/hnatt/code/faye/lib/faye/protocol/server.rb:66:in `block in process'
        from /home/hnatt/code/faye/lib/faye/protocol/server.rb:65:in `each'
        from /home/hnatt/code/faye/lib/faye/protocol/server.rb:65:in `process'
        from /home/hnatt/code/faye/lib/faye/adapters/rack_adapter.rb:132:in `block in handle_request'
        from /home/hnatt/.rbenv/versions/2.2.3/lib/ruby/gems/2.2.0/gems/eventmachine-1.0.8/lib/eventmachine.rb:976:in `call'
        from /home/hnatt/.rbenv/versions/2.2.3/lib/ruby/gems/2.2.0/gems/eventmachine-1.0.8/lib/eventmachine.rb:976:in `block in run_deferred_callbacks'
        from /home/hnatt/.rbenv/versions/2.2.3/lib/ruby/gems/2.2.0/gems/eventmachine-1.0.8/lib/eventmachine.rb:973:in `times'
        from /home/hnatt/.rbenv/versions/2.2.3/lib/ruby/gems/2.2.0/gems/eventmachine-1.0.8/lib/eventmachine.rb:973:in `run_deferred_callbacks'
        from /home/hnatt/.rbenv/versions/2.2.3/lib/ruby/gems/2.2.0/gems/eventmachine-1.0.8/lib/eventmachine.rb:193:in `run_machine'
        from /home/hnatt/.rbenv/versions/2.2.3/lib/ruby/gems/2.2.0/gems/eventmachine-1.0.8/lib/eventmachine.rb:193:in `run'
        from /home/hnatt/.rbenv/versions/2.2.3/lib/ruby/gems/2.2.0/gems/thin-1.6.4/lib/thin/backends/base.rb:73:in `start'
        from /home/hnatt/.rbenv/versions/2.2.3/lib/ruby/gems/2.2.0/gems/thin-1.6.4/lib/thin/server.rb:162:in `start'
        from /home/hnatt/.rbenv/versions/2.2.3/lib/ruby/gems/2.2.0/gems/rack-1.6.4/lib/rack/handler/thin.rb:19:in `run'
        from /home/hnatt/.rbenv/versions/2.2.3/lib/ruby/gems/2.2.0/gems/rack-1.6.4/lib/rack/server.rb:286:in `start'
        from /home/hnatt/.rbenv/versions/2.2.3/lib/ruby/gems/2.2.0/gems/rack-1.6.4/lib/rack/server.rb:147:in `start'
        from /home/hnatt/.rbenv/versions/2.2.3/lib/ruby/gems/2.2.0/gems/rack-1.6.4/bin/rackup:4:in `<top (required)>'
        from /home/hnatt/.rbenv/versions/2.2.3/bin/rackup:23:in `load'
        from /home/hnatt/.rbenv/versions/2.2.3/bin/rackup:23:in `<main>'
```

Running with `thin` command, the server also fails, writing the same message to the log.

**Comment by jcoglan** [comment]
Okay, that should have thrown an error here: https://github.com/faye/faye/blob/master/lib/faye/adapters/rack_adapter.rb#L113 because `1` is not a valid JSON string, and that error would be caught here if it were raised: https://github.com/faye/faye/blob/master/lib/faye/adapters/rack_adapter.rb#L148

Which JSON library are you running with `MultiJson`?

**Comment by hnatt** [comment]
`json` gem version `1.8.3`

**Comment by jcoglan** [comment]
This should be fixed in https://github.com/faye/faye/commit/210a870601c1cd64217416c289a710fb07f31e44.

**Comment by jcoglan** [comment]
Apologies, that commit contains an error, see https://github.com/faye/faye/commit/a3d767210f6fcaac16e6b6d3be7e4b01d4ecbcb5 instead.
