### ISSUE TITLE
lib/faye/protocol/server.rb:206:in `+': no implicit conversion of nil into Array

### ISSUE THREAD

**Issue by artworx** [faye/faye#440]
```
/home/artworx/.rvm/gems/ruby-2.3.0@chat/gems/faye-1.1.2/lib/faye/protocol/server.rb:206:in `+': no implicit conversion of nil into Array (TypeError)
        from /home/artworx/.rvm/gems/ruby-2.3.0@chat/gems/faye-1.1.2/lib/faye/protocol/server.rb:206:in `block (2 levels) in connect'
        from /home/artworx/.rvm/gems/ruby-2.3.0@chat/gems/eventmachine-1.2.0.1/lib/em/deferrable.rb:156:in `set_deferred_status'
        from /home/artworx/.rvm/gems/ruby-2.3.0@chat/gems/faye-1.1.2/lib/faye/mixins/deferrable.rb:10:in `set_deferred_status'
        from /home/artworx/.rvm/gems/ruby-2.3.0@chat/gems/faye-1.1.2/lib/faye/engines/connection.rb:39:in `flush'
        from /home/artworx/.rvm/gems/ruby-2.3.0@chat/gems/faye-1.1.2/lib/faye/engines/connection.rb:49:in `block in begin_delivery_timeout'
        from /home/artworx/.rvm/gems/ruby-2.3.0@chat/gems/faye-1.1.2/lib/faye/mixins/timeouts.rb:9:in `block in add_timeout'
        from /home/artworx/.rvm/gems/ruby-2.3.0@chat/gems/eventmachine-1.2.0.1/lib/eventmachine.rb:194:in `run_machine'
        from /home/artworx/.rvm/gems/ruby-2.3.0@chat/gems/eventmachine-1.2.0.1/lib/eventmachine.rb:194:in `run'
        from /home/artworx/source/experiments/chat/config.ru:13:in `block in <main>'
        from /home/artworx/.rvm/gems/ruby-2.3.0@chat/gems/rack-1.6.4/lib/rack/builder.rb:55:in `instance_eval'
        from /home/artworx/.rvm/gems/ruby-2.3.0@chat/gems/rack-1.6.4/lib/rack/builder.rb:55:in `initialize'
        from /home/artworx/source/experiments/chat/config.ru:in `new'
        from /home/artworx/source/experiments/chat/config.ru:in `<main>'
        from /home/artworx/.rvm/gems/ruby-2.3.0@chat/gems/rack-1.6.4/lib/rack/builder.rb:49:in `eval'
        from /home/artworx/.rvm/gems/ruby-2.3.0@chat/gems/rack-1.6.4/lib/rack/builder.rb:49:in `new_from_string'
        from /home/artworx/.rvm/gems/ruby-2.3.0@chat/gems/rack-1.6.4/lib/rack/builder.rb:40:in `parse_file'
        from /home/artworx/.rvm/gems/ruby-2.3.0@chat/gems/rack-1.6.4/lib/rack/server.rb:299:in `build_app_and_options_from_config'
        from /home/artworx/.rvm/gems/ruby-2.3.0@chat/gems/rack-1.6.4/lib/rack/server.rb:208:in `app'
        from /home/artworx/.rvm/gems/ruby-2.3.0@chat/gems/rack-1.6.4/lib/rack/server.rb:336:in `wrapped_app'
        from /home/artworx/.rvm/gems/ruby-2.3.0@chat/gems/rack-1.6.4/lib/rack/server.rb:272:in `start'
        from /home/artworx/.rvm/gems/ruby-2.3.0@chat/gems/rack-1.6.4/lib/rack/server.rb:147:in `start'
        from /home/artworx/.rvm/gems/ruby-2.3.0@chat/gems/rack-1.6.4/bin/rackup:4:in `<top (required)>'
        from /home/artworx/.rvm/gems/ruby-2.3.0@chat/bin/rackup:23:in `load'
        from /home/artworx/.rvm/gems/ruby-2.3.0@chat/bin/rackup:23:in `<main>'
        from /home/artworx/.rvm/gems/ruby-2.3.0@chat/bin/ruby_executable_hooks:15:in `eval'
        from /home/artworx/.rvm/gems/ruby-2.3.0@chat/bin/ruby_executable_hooks:15:in `<main>
```

Here is the application i am using: https://gist.github.com/artworx/10ed77d8f8dcdf5a2c4610037d046f7a

Every version after 1.0.3 of faye crashes with this error.

**Comment by jcoglan** [comment]
Thanks for reporting this error. 8a20009 should fix things.
