### ISSUE TITLE
bad argument (expected URI object or URI string) running thin start -R examples/ruby/config.ru

### ISSUE THREAD

**Issue by stepheneb** [faye/faye#452]
Am testing the ruby server version of faye by having the gem repo checked out locally running `bundle install` and running `examples/ruby/config.ru`.

When I load the web page line 25 in dispatcher.rb generates an error calling `URI(endpoint)`.

`endpoint` is a `Faye::Server` object and doesn't appear to provide a URI object or URI string.

```
[faye ruby-2.3.1 (master)]$ bundle exec thin start -R examples/ruby/config.ru -p 9292

Unexpected error while processing request: bad argument (expected URI object or URI string)
    /Users/stephen/.rbenv/versions/2.3.1/lib/ruby/2.3.0/uri/common.rb:716:in `URI'
    /Users/stephen/dev/ruby/gems/faye/lib/faye/protocol/dispatcher.rb:25:in `initialize'
    /Users/stephen/dev/ruby/gems/faye/lib/faye/protocol/client.rb:29:in `new'
    /Users/stephen/dev/ruby/gems/faye/lib/faye/protocol/client.rb:29:in `initialize'
    /Users/stephen/dev/ruby/gems/faye/lib/faye/adapters/rack_adapter.rb:72:in `new'
    /Users/stephen/dev/ruby/gems/faye/lib/faye/adapters/rack_adapter.rb:72:in `get_client'
    /Users/stephen/dev/ruby/gems/faye/lib/faye/adapters/rack_adapter.rb:80:in `call'
    /Users/stephen/.rbenv/versions/2.3.1/lib/ruby/gems/2.3.0/gems/thin-1.7.0/lib/thin/connection.rb:86:in `block in pre_process'
    /Users/stephen/.rbenv/versions/2.3.1/lib/ruby/gems/2.3.0/gems/thin-1.7.0/lib/thin/connection.rb:84:in `catch'
    /Users/stephen/.rbenv/versions/2.3.1/lib/ruby/gems/2.3.0/gems/thin-1.7.0/lib/thin/connection.rb:84:in `pre_process'
    /Users/stephen/.rbenv/versions/2.3.1/lib/ruby/gems/2.3.0/gems/thin-1.7.0/lib/thin/connection.rb:53:in `process'
    /Users/stephen/.rbenv/versions/2.3.1/lib/ruby/gems/2.3.0/gems/faye-websocket-0.10.4/lib/faye/adapters/thin.rb:41:in `process'
    /Users/stephen/.rbenv/versions/2.3.1/lib/ruby/gems/2.3.0/gems/thin-1.7.0/lib/thin/connection.rb:39:in `receive_data'
    /Users/stephen/.rbenv/versions/2.3.1/lib/ruby/gems/2.3.0/gems/faye-websocket-0.10.4/lib/faye/adapters/thin.rb:46:in `receive_data'
    /Users/stephen/.rbenv/versions/2.3.1/lib/ruby/gems/2.3.0/gems/eventmachine-1.2.0.1/lib/eventmachine.rb:194:in `run_machine'
    /Users/stephen/.rbenv/versions/2.3.1/lib/ruby/gems/2.3.0/gems/eventmachine-1.2.0.1/lib/eventmachine.rb:194:in `run'
    /Users/stephen/.rbenv/versions/2.3.1/lib/ruby/gems/2.3.0/gems/thin-1.7.0/lib/thin/backends/base.rb:73:in `start'
    /Users/stephen/.rbenv/versions/2.3.1/lib/ruby/gems/2.3.0/gems/thin-1.7.0/lib/thin/server.rb:162:in `start'
    /Users/stephen/.rbenv/versions/2.3.1/lib/ruby/gems/2.3.0/gems/thin-1.7.0/lib/thin/controllers/controller.rb:87:in `start'
    /Users/stephen/.rbenv/versions/2.3.1/lib/ruby/gems/2.3.0/gems/thin-1.7.0/lib/thin/runner.rb:200:in `run_command'
    /Users/stephen/.rbenv/versions/2.3.1/lib/ruby/gems/2.3.0/gems/thin-1.7.0/lib/thin/runner.rb:156:in `run!'
    /Users/stephen/.rbenv/versions/2.3.1/lib/ruby/gems/2.3.0/gems/thin-1.7.0/bin/thin:6:in `<top (required)>'
    /Users/stephen/.rbenv/versions/2.3.1/bin/thin:23:in `load'
    /Users/stephen/.rbenv/versions/2.3.1/bin/thin:23:in `<top (required)>'
    /Users/stephen/.rbenv/versions/2.3.1/lib/ruby/gems/2.3.0/gems/bundler-1.13.2/lib/bundler/cli/exec.rb:74:in `load'
    /Users/stephen/.rbenv/versions/2.3.1/lib/ruby/gems/2.3.0/gems/bundler-1.13.2/lib/bundler/cli/exec.rb:74:in `kernel_load'
    /Users/stephen/.rbenv/versions/2.3.1/lib/ruby/gems/2.3.0/gems/bundler-1.13.2/lib/bundler/cli/exec.rb:27:in `run'
    /Users/stephen/.rbenv/versions/2.3.1/lib/ruby/gems/2.3.0/gems/bundler-1.13.2/lib/bundler/cli.rb:332:in `exec'
    /Users/stephen/.rbenv/versions/2.3.1/lib/ruby/gems/2.3.0/gems/bundler-1.13.2/lib/bundler/vendor/thor/lib/thor/command.rb:27:in `run'
    /Users/stephen/.rbenv/versions/2.3.1/lib/ruby/gems/2.3.0/gems/bundler-1.13.2/lib/bundler/vendor/thor/lib/thor/invocation.rb:126:in `invoke_command'
    /Users/stephen/.rbenv/versions/2.3.1/lib/ruby/gems/2.3.0/gems/bundler-1.13.2/lib/bundler/vendor/thor/lib/thor.rb:359:in `dispatch'
    /Users/stephen/.rbenv/versions/2.3.1/lib/ruby/gems/2.3.0/gems/bundler-1.13.2/lib/bundler/cli.rb:20:in `dispatch'
    /Users/stephen/.rbenv/versions/2.3.1/lib/ruby/gems/2.3.0/gems/bundler-1.13.2/lib/bundler/vendor/thor/lib/thor/base.rb:440:in `start'
    /Users/stephen/.rbenv/versions/2.3.1/lib/ruby/gems/2.3.0/gems/bundler-1.13.2/lib/bundler/cli.rb:11:in `start'
    /Users/stephen/.rbenv/versions/2.3.1/lib/ruby/gems/2.3.0/gems/bundler-1.13.2/exe/bundle:34:in `block in <top (required)>'
    /Users/stephen/.rbenv/versions/2.3.1/lib/ruby/gems/2.3.0/gems/bundler-1.13.2/lib/bundler/friendly_errors.rb:100:in `with_friendly_errors'
    /Users/stephen/.rbenv/versions/2.3.1/lib/ruby/gems/2.3.0/gems/bundler-1.13.2/exe/bundle:26:in `<top (required)>'
    /Users/stephen/.rbenv/versions/2.3.1/bin/bundle:23:in `load'
    /Users/stephen/.rbenv/versions/2.3.1/bin/bundle:23:in `<main>'
```

Have seen the same error running in Ruby 2.2.5 and 2.1.10

**Comment by stepheneb** [comment]
This bug introduced in c0e135911f

**Comment by jcoglan** [comment]
Does this fix the problem? https://github.com/faye/faye/commit/bd01bc7c0a5885afe933392087a4708a25021675

**Comment by stepheneb** [comment]
Yes. Thanks
