### ISSUE TITLE
Unexpected error while processing request: uninitialized constant EventMachine::Deferrable::Rails

### ISSUE THREAD

**Issue by imi56** [faye/faye#527]
`faye` server is throwing the following error **uninitialized constant EventMachine::Rails (NameError)** on connection.
In the browser getting **WebSocket connection to 'wss://xyz.com/faye' failed: Error during WebSocket handshake: Unexpected response code: 502**
This problem is somewhat similar to [this issue](https://github.com/eventmachine/eventmachine/issues/773) but no hlep.
```
Full trace:
Traceback (most recent call last):
        10: from /opt/rubies/ruby-2.5.7/bin/rackup:23:in `<main>'
         9: from /opt/rubies/ruby-2.5.7/bin/rackup:23:in `load'
         8: from /opt/rubies/ruby-2.5.7/lib/ruby/gems/2.5.0/gems/rack-1.6.12/bin/rackup:4:in `<top (required)>'
         7: from /opt/rubies/ruby-2.5.7/lib/ruby/gems/2.5.0/gems/rack-1.6.12/lib/rack/server.rb:148:in `start'
         6: from /opt/rubies/ruby-2.5.7/lib/ruby/gems/2.5.0/gems/rack-1.6.12/lib/rack/server.rb:287:in `start'
         5: from /opt/rubies/ruby-2.5.7/lib/ruby/gems/2.5.0/gems/rack-1.6.12/lib/rack/handler/thin.rb:19:in `run'
         4: from /opt/rubies/ruby-2.5.7/lib/ruby/gems/2.5.0/gems/thin-1.7.2/lib/thin/server.rb:162:in `start'
         3: from /opt/rubies/ruby-2.5.7/lib/ruby/gems/2.5.0/gems/thin-1.7.2/lib/thin/backends/base.rb:73:in `start'
         2: from /opt/rubies/ruby-2.5.7/lib/ruby/gems/2.5.0/gems/eventmachine-1.2.7/lib/eventmachine.rb:195:in `run'
         1: from /opt/rubies/ruby-2.5.7/lib/ruby/gems/2.5.0/gems/eventmachine-1.2.7/lib/eventmachine.rb:195:in `run_machine'
/opt/rubies/ruby-2.5.7/lib/ruby/gems/2.5.0/gems/eventmachine-1.2.7/lib/eventmachine.rb:968:in `run_deferred_callbacks': uninitialized constant EventMachine::Rails (NameError)
```
Gem version & dependencies
```
faye (1.3.0)
      cookiejar (>= 0.3.0)
      em-http-request (>= 0.3.0)
      eventmachine (>= 0.12.0)
      faye-websocket (>= 0.9.1)
      multi_json (>= 1.0.0)
      rack (>= 1.0.0)
      websocket-driver (>= 0.5.1)
    faye-websocket (0.10.7)
      eventmachine (>= 0.12.0)
```

**Comment by jcoglan** [comment]
Neither EventMachine nor Faye refers to `Rails` anywhere in their codebases. Have you bound any event listeners to Faye that depend on anything from Rails or your application?

**Comment by imi56** [comment]
No. Just establishing the connection and alerting the receiving data.
Here is the coffee code.
```
$(document).ready ->
  // $("#data-faye").data().faye_host => returns the server url e.g. https://xyz.com/faye on staging and http://localhost:9292/faye on dev env
  url = $("#data-faye").data().faye_host
  faye = new (Faye.Client)(url)
  faye.subscribe '/test', (data) ->
    alert data
    return
```

**Comment by imi56** [comment]
Actually when page loads `faye` server is getting killed. The very first error is
**Unexpected error while processing request: uninitialized constant EventMachine::Deferrable::Rails**
followed by **uninitialized constant EventMachine::Rails**
Full trace:
```
Unexpected error while processing request: uninitialized constant EventMachine::Deferrable::Rails
        /opt/rubies/ruby-2.5.7/lib/ruby/gems/2.5.0/gems/eventmachine-1.2.7/lib/em/deferrable.rb:73:in `errback'
        /opt/rubies/ruby-2.5.7/lib/ruby/gems/2.5.0/gems/thin-1.7.2/lib/thin/connection.rb:127:in `post_process'
        /opt/rubies/ruby-2.5.7/lib/ruby/gems/2.5.0/gems/faye-websocket-0.10.7/lib/faye/websocket.rb:80:in `call'
        /opt/rubies/ruby-2.5.7/lib/ruby/gems/2.5.0/gems/faye-websocket-0.10.7/lib/faye/websocket.rb:80:in `initialize'
        /opt/rubies/ruby-2.5.7/lib/ruby/gems/2.5.0/gems/faye-1.3.0/lib/faye/adapters/rack_adapter.rb:195:in `new'
        /opt/rubies/ruby-2.5.7/lib/ruby/gems/2.5.0/gems/faye-1.3.0/lib/faye/adapters/rack_adapter.rb:195:in `handle_websocket'
        /opt/rubies/ruby-2.5.7/lib/ruby/gems/2.5.0/gems/faye-1.3.0/lib/faye/adapters/rack_adapter.rb:92:in `call'
        /opt/rubies/ruby-2.5.7/lib/ruby/gems/2.5.0/gems/thin-1.7.2/lib/thin/connection.rb:86:in `block in pre_process'
        /opt/rubies/ruby-2.5.7/lib/ruby/gems/2.5.0/gems/thin-1.7.2/lib/thin/connection.rb:84:in `catch'
        /opt/rubies/ruby-2.5.7/lib/ruby/gems/2.5.0/gems/thin-1.7.2/lib/thin/connection.rb:84:in `pre_process'
        /opt/rubies/ruby-2.5.7/lib/ruby/gems/2.5.0/gems/thin-1.7.2/lib/thin/connection.rb:53:in `process'
        /opt/rubies/ruby-2.5.7/lib/ruby/gems/2.5.0/gems/thin-1.7.2/lib/thin/connection.rb:39:in `receive_data'
        /opt/rubies/ruby-2.5.7/lib/ruby/gems/2.5.0/gems/eventmachine-1.2.7/lib/eventmachine.rb:195:in `run_machine'
        /opt/rubies/ruby-2.5.7/lib/ruby/gems/2.5.0/gems/eventmachine-1.2.7/lib/eventmachine.rb:195:in `run'
        /opt/rubies/ruby-2.5.7/lib/ruby/gems/2.5.0/gems/thin-1.7.2/lib/thin/backends/base.rb:73:in `start'
        /opt/rubies/ruby-2.5.7/lib/ruby/gems/2.5.0/gems/thin-1.7.2/lib/thin/server.rb:162:in `start'
        /opt/rubies/ruby-2.5.7/lib/ruby/gems/2.5.0/gems/rack-1.6.12/lib/rack/handler/thin.rb:19:in `run'
        /opt/rubies/ruby-2.5.7/lib/ruby/gems/2.5.0/gems/rack-1.6.12/lib/rack/server.rb:287:in `start'
        /opt/rubies/ruby-2.5.7/lib/ruby/gems/2.5.0/gems/rack-1.6.12/lib/rack/server.rb:148:in `start'
        /opt/rubies/ruby-2.5.7/lib/ruby/gems/2.5.0/gems/rack-1.6.12/bin/rackup:4:in `<top (required)>'
        /opt/rubies/ruby-2.5.7/bin/rackup:23:in `load'
        /opt/rubies/ruby-2.5.7/bin/rackup:23:in `<main>'

Traceback (most recent call last):
        10: from /opt/rubies/ruby-2.5.7/bin/rackup:23:in `<main>'
         9: from /opt/rubies/ruby-2.5.7/bin/rackup:23:in `load'
         8: from /opt/rubies/ruby-2.5.7/lib/ruby/gems/2.5.0/gems/rack-1.6.12/bin/rackup:4:in `<top (required)>'
         7: from /opt/rubies/ruby-2.5.7/lib/ruby/gems/2.5.0/gems/rack-1.6.12/lib/rack/server.rb:148:in `start'
         6: from /opt/rubies/ruby-2.5.7/lib/ruby/gems/2.5.0/gems/rack-1.6.12/lib/rack/server.rb:287:in `start'
         5: from /opt/rubies/ruby-2.5.7/lib/ruby/gems/2.5.0/gems/rack-1.6.12/lib/rack/handler/thin.rb:19:in `run'
         4: from /opt/rubies/ruby-2.5.7/lib/ruby/gems/2.5.0/gems/thin-1.7.2/lib/thin/server.rb:162:in `start'
         3: from /opt/rubies/ruby-2.5.7/lib/ruby/gems/2.5.0/gems/thin-1.7.2/lib/thin/backends/base.rb:73:in `start'
         2: from /opt/rubies/ruby-2.5.7/lib/ruby/gems/2.5.0/gems/eventmachine-1.2.7/lib/eventmachine.rb:195:in `run'
         1: from /opt/rubies/ruby-2.5.7/lib/ruby/gems/2.5.0/gems/eventmachine-1.2.7/lib/eventmachine.rb:195:in `run_machine'
/opt/rubies/ruby-2.5.7/lib/ruby/gems/2.5.0/gems/eventmachine-1.2.7/lib/eventmachine.rb:968:in `run_deferred_callbacks': uninitialized constant EventMachine::Rails
```

**Comment by jcoglan** [comment]
None of the lines in this backtrace refer to the constant `Rails`, but a lot of them are concerned with running callbacks that will yield to user-supplied code. Your Faye server setup code does not appear to reference anything from Rails, or load application code, and does not set up any event listeners or extensions:

```ruby
require "faye"
faye_server = Faye::RackAdapter.new(:mount => '/faye', :timeout => 45)
run faye_server
```

The one problem I can see with this is that it sets the `timeout` to `45`, which is greater than the Thin request timeout limit of `30`. This may cause weird results.

What command are you using to start the server in `faye.ru`?

**Comment by imi56** [comment]
Updated the `faye.ru`
```
require 'faye'
Faye::WebSocket.load_adapter('thin')
faye_server = Faye::RackAdapter.new(:mount => '/faye', :timeout => 25)
run faye_server
```
Ran the server in both ways but the same issue popping up on page load.

1. `thin -p 9292 -t 60 -R faye.ru start`
2. `rackup faye.ru -s thin -E production`

**Comment by imi56** [comment]
> Neither EventMachine nor Faye refers to Rails anywhere in their codebases
Yes, you were right, while debugging other issues, there was some bad code left in the gem.
Sorry to bother you, and thanks for quick responses.
